name: sisonke
description: Simple tasbeeh application that helps muslims dzikr activity.


publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get_it: ^7.2.0
  provider: ^6.0.3
  connectivity: ^3.0.6
  dio: ^5.1.1
  http: ^0.13.4
  freezed: ^2.1.0+1
  shared_preferences: ^2.0.15
  fancy_bottom_navigation: ^0.3.3
  carousel_slider: ^4.1.1
  flutter_staggered_grid_view: ^0.6.2
  shimmer: ^2.0.0
  url_launcher: ^6.1.5
  image_picker: ^0.8.5+3
  webview_flutter: ^4.2.0
  flutter_html: ^3.0.0-alpha.5
  share: ^2.0.4
  photo_view: ^0.14.0
  package_info: ^2.0.2
  firebase_core: ^2.11.0
  firebase_messaging: ^14.5.0
  flutter_local_notifications: ^14.0.0+1
  path_provider: ^2.0.11
  flutter_svg: ^2.0.5
  phone_number: ^1.0.0 
  country_code_picker: ^3.0.0
  pin_code_fields: ^7.4.0
  otp_text_field: ^1.1.3
  flutter_switch: ^0.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/

  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/titillium/TitilliumWeb-Regular.ttf
        - asset: assets/fonts/titillium/TitilliumWeb-Italic.ttf
        - asset: assets/fonts/titillium/TitilliumWeb-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/titillium/TitilliumWeb-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700

    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
